### ISSUE TITLE
error computing authrep credentials error

### ISSUE THREAD

**Issue by dkoci** [3scale/threescale-wasm-auth#118]
I configured everrything as it should be. Error in istio sidecar container is:

```
2024-07-25T13:54:34.643341Z	error	envoy wasm	wasm log travel-agency.travel-agency:    2746300832 (1/http): error computing authrep credentials error

Caused by:
    credentials not found
```

**Comment by tkan145** [comment]
Hi, can you share the minimum configuration and steps you used please?

**Comment by dkoci** [comment]
> Hi, can you share the minimum configuration and steps you used please?

I deployed some demo app. It was working fine with Istio Service Mesh until i deployed WasmPlugin CR.

```yaml
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
 name: travel-agency
spec:
 url: oci://quay.io/3scale/threescale-wasm-auth:v1.0.0
 phase: AUTHZ
 priority: 100
 match:
   - mode: SERVER
 selector:
   matchLabels:
     app: travels
     version: v1
 pluginConfig:
   api: v1
   system:
     name: system
     token: XXXXXXXXXXXX (I omit access token from 3Scale system-seed)
     upstream:
       name: >-
         outbound|3000||system-provider.3scale.svc.cluster.local
       timeout: 5000
       url: 'http://system-provider.3scale.svc.cluster.local'
   backend:
     extensions:
       - no_body
     name: backend
     upstream:
       name: >-
         outbound|3000||backend-listener.3scale.svc.cluster.local
       timeout: 5000
       url: 'http://backend-listener.3scale.svc.cluster.local'
   services:
     - id: '3'
       token: XXXXXXXXXXXX (I omit 3Scale product service token)
       authorities:
         - '*'
       credentials:
         user_key:
           - query_string:
               keys:
                 - user_key
           - header:
               keys:
                 - user_key
       mapping_rules:
         - method: GET
           pattern: /
           usages:
             - delta: 1
               name: hits
```

I also created system and backend ServiceEntry CR:

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
 name: system-entry
 namespace: travel-agency
spec:
 hosts:
   - system-provider.3scale.svc.cluster.local
 location: MESH_EXTERNAL
 ports:
   - name: http
     number: 3000
     protocol: HTTP
 resolution: DNS
```

```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
 name: backend-entry
 namespace: travel-agency
spec:
 hosts:
   - backend-listener.3scale.svc.cluster.local
 location: MESH_EXTERNAL
 ports:
   - name: http
     number: 3000
     protocol: HTTP
 resolution: DNS
```

I created 3Scale product, application plan and application. I also configured product to use Istio and user_key authentication:
<img width="764" alt="image" src="https://github.com/user-attachments/assets/699984e9-2241-4d11-ae9a-8fc8f095d9b5">

When I try to call the service I get no response. Thre is an error in istio-proxy sidecar container:
```
error	envoy wasm	wasm log travel-agency.travel-agency:    2746300832 (1/http): error computing authrep credentials error

Caused by:
    credentials not found
```
