### ISSUE TITLE
Empty VM config error with ServiceMeshExtension

### ISSUE THREAD

**Issue by pehala** [3scale/threescale-wasm-auth#54]
I am getting empty VM config.
`2021-09-01T08:53:50.607940Z	warning	envoy wasm	wasm log threescale-auth_root :  (root/1) 3308815210: on_vm_start: empty VM config`

With this configuration and my custom builder image from master (It also didn't work with the qe image)
```
spec:
  config:
    api: v1
    backend:
      extensions:
        - no_body
      name: backend-name
      upstream:
        name: >-
          outbound|443||backend-3scale.3scale.apps.ocp-cluster.osp.api-qe.eng.rdu2.redhat.com
        timeout: 5000
        url: >-
          https://backend-3scale.3scale.apps.ocp-cluster.osp.api-qe.eng.rdu2.redhat.com/
    services:
      - authorities:
          - '*'
        credentials:
          app_id:
            - header:
                keys:
                  - x-app-id
            - query_string:
                keys:
                  - app_id
                  - application_id
            - filter:
                keys:
                  - azp
                  - aud
                path:
                  - envoy.filters.http.jwt_authn
                  - '0'
            - header:
                keys:
                  - x-jwt-payload
                ops:
                  - decode: base64_urlsafe
                  - format:
                      json:
                        keys:
                          - azp
                          - aud
                        path: []
            - header:
                keys:
                  - authorization
                ops:
                  - format:
                      joined:
                        indexes:
                          - 1
                        max: 2
                        separator: ' '
                  - decode: base64_urlsafe
                  - format:
                      joined:
                        indexes:
                          - 0
                          - 1
                        max: 2
                        separator: ':'
          app_key:
            - header:
                keys:
                  - x-app-key
            - query_string:
                keys:
                  - app_key
                  - application_key
          user_key:
            - query_string:
                keys:
                  - api_key
                ops:
                  - format:
                      joined:
                        indexes:
                          - 0
                        max: 2
                        separator: ':'
        id: '209'
        mapping_rules:
          - method: GET
            pattern: /
            usages:
              - delta: 1
                name: Hits
        token: thetoken
    system:
      name: system-name
      token: thetoken
      upstream:
        name: >-
          outbound|443||3scale-admin.3scale.apps.ocp-cluster.osp.api-qe.eng.rdu2.redhat.com
        timeout: 5000
        url: >-
          https://3scale-admin.3scale.apps.ocp-cluster.osp.api-qe.eng.rdu2.redhat.com/
  image: 'quay.io/phala/threescale-wasm-auth:latest'
  phase: PostAuthZ
  priority: 100
  workloadSelector:
    labels:
      app: httpbin
```

It looks like I have wrong configuration but I cant figure out what exactly is wrong.
